### ISSUE TITLE
Help getting started 

### ISSUE THREAD

**Issue by bnm12** [burningice2866/CompositeC1Contrib.FormBuilder#1]
Hey,

I'm trying (and failing) to figure out how to use the FormBuilder POCO module, but I can't for the life of me figure out how and where you define a form, and how you use it, I have some sample code from here: https://github.com/burningice2866/CompositeC1Contrib.Security/issues/1#issuecomment-231727278

Which clearly seems to be a C# class of some description, but where do I put it? The only close thing I've been able to find in Composite is that with this FormBuilder module you can add new razor functions to the formbuilder functions folder.

Any pointers would be greatly appreciated :)

**Comment by burningice2866** [comment]
@bnm12 Hey again :)

The principle of POCO forms is based on The FormBuilder package which lays the foundation for defining, registering and rendering forms within C1 and the POCO package which builds on top of FormBuilder and provides forms and handles its lifetime from C# code.

So the first thing to make sure is that FormBuilder is installed correctly, that is [its Element and Function providers in composite.config and some configuration in web.config](https://github.com/burningice2866/CompositeC1Contrib.FormBuilder/tree/master/FormBuilder/Package/config), and [some content files](https://github.com/burningice2866/CompositeC1Contrib.FormBuilder/tree/master/FormBuilder/Package) which are copied to App_Data/Razor, Frontend and Composite folders.

Lastly you need to make sure to register/invoke the FormBuilder using its [UseCompositeC1ContribFormBuilder Owin Extension method](https://github.com/burningice2866/CompositeC1Contrib.FormBuilder/blob/master/FormBuilder/Web/OwinExtensions.cs#L16) like this

`app.UseCompositeC1ContribFormBuilder(httpConfiguration)`

Beware that FormBuilder uses WebApi to define its api endpoints, so a complete example could be like this

```
public void Configuration(IAppBuilder app)
{
    GlobalConfiguration.Configure(httpConfiguration =>
    {
        app.UseCompositeC1ContribFormBuilder(httpConfiguration);
    });
}
```

When that is working, the POCO package only consists of a single dll-file that should be referenced from your project where the forms are defined.

POCO forms are defined by a public class that implements the IPOCOForm and has a [FormName("...", "...")] attribute, where the first argument is its namespace and the second its name. This corresponds to the Function that will be auto-generated in C1 for this function. That means that Forms will automatically show up in the Console for the editor to insert, and you can insert them in templates as well as any other function. This is what we refer to as the Controller and Model combined in one class.

One caveat at the moment, which i haven't gone and fixed yet, is that if you just goes ahead and inserts the form-function on a page, you'll get an exception saying that the function can't be executed due to wrong context, or something like that. You fix this issue by going ahead and copying the [existing StandardFormExecutor.cshtml Razor-function](https://github.com/burningice2866/CompositeC1Contrib.FormBuilder/blob/master/FormBuilder/Package/content/App_Data/Razor/FormBuilder/StandardFormExecutor.cshtml) and give it the same name as the Form, and let it inherit from `POCOBasedFormsPage<T>` where T is the type of your form. This is what we refer to as the View.

You are now free to change the content of the function - ie. can you render individual fields instead of all of them at once using `@FieldFor(f => f....)` and other nifty helper functions that give you strongly typed access to your form.

In my experience you would almost always go ahead and create a custom view for your POCO form, which is why i haven't gone and fixed the issue of rendering POCO forms without a custom view.

**Comment by burningice2866** [comment]
Further discussion related to this issue can be read here https://gitter.im/burningice2866/CompositeC1Contrib.FormBuilder?at=578757213c5129720e1b0fcb
